Update updater_from_source.py
Error observed (see below) due to typo as there is no attribute "remove_finding.from_any_risk_acceptance" but "remove_finding_from_risk_acceptance" in dojo.risk_acceptance.helper

django-defectdojo-290-celeryworker-1  | [07/May/2022 06:45:11] INFO [celery.worker.strategy:161] Task dojo.tools.tool_issue_updater.update_findings_from_source_issues[361fe131-8388-4cab-a57c-babcf7277fe6] received
django-defectdojo-290-celeryworker-1  | [07/May/2022 06:45:13] INFO [dojo.tools.sonarqube_api.updater_from_source:42] Original SonarQube issue 'AXdSCynZxatigMswcPxy' has changed. Updating DefectDojo finding 'Disable Access to External Entities in XML Parsing.'...
django-defectdojo-290-celeryworker-1  | [07/May/2022 06:45:13] ERROR [celery.app.trace:265] Task dojo.tools.tool_issue_updater.update_findings_from_source_issues[361fe131-8388-4cab-a57c-babcf7277fe6] raised unexpected: AttributeError("module 'dojo.risk_acceptance.helper' has no attribute 'remove_finding'")
django-defectdojo-290-celeryworker-1  | Traceback (most recent call last):
django-defectdojo-290-celeryworker-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
django-defectdojo-290-celeryworker-1  |     R = retval = fun(*args, **kwargs)
django-defectdojo-290-celeryworker-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
django-defectdojo-290-celeryworker-1  |     return self.run(*args, **kwargs)
django-defectdojo-290-celeryworker-1  |   File "/app/dojo/tools/tool_issue_updater.py", line 40, in update_findings_from_source_issues
django-defectdojo-290-celeryworker-1  |     SonarQubeApiUpdaterFromSource().update(finding)
django-defectdojo-290-celeryworker-1  |   File "/app/dojo/tools/sonarqube_api/updater_from_source.py", line 45, in update
django-defectdojo-290-celeryworker-1  |     self.update_finding_status(finding, current_status)
django-defectdojo-290-celeryworker-1  |   File "/app/dojo/tools/sonarqube_api/updater_from_source.py", line 87, in update_finding_status
django-defectdojo-290-celeryworker-1  |     ra_helper.remove_finding.from_any_risk_acceptance(finding)
django-defectdojo-290-celeryworker-1  | AttributeError: module 'dojo.risk_acceptance.helper' has no attribute 'remove_finding'
django-defectdojo-290-celeryworker-1  | [07/May/2022 06:45:13] INFO [celery.worker.strategy:161] Task dojo.tasks.add_alerts[c180110e-8503-46b9-af4c-a65b1880cb02] received